name: Firebase App Distribution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug or release)'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
        
    - name: Create google-services.json
      run: |
        cat > app/google-services.json << 'EOF'
        ${{ secrets.GOOGLE_SERVICES_JSON }}
        EOF
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build debug APK and distribute
      if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'debug')
      run: ./gradlew :app:assembleDebug :app:appDistributionUploadDebug
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Build release APK and distribute
      if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'release')
      run: ./gradlew :app:assembleRelease :app:appDistributionUploadRelease
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-android-apk
        path: app/build/outputs/apk/**/*.apk
        retention-days: 30